name: ha_floating_demo
description: Ha Floating Demo - File Manager kiểu Filza cho iOS
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  # Chọn file từ thiết bị
  file_picker: ^8.1.2
  # Lấy đường dẫn chuẩn của app
  path_provider: ^2.1.3
  # Xin quyền truy cập file
  permission_handler: ^11.3.1
  # Mở file bằng app mặc định
  open_file: ^3.3.2
  # Animation mượt
  flutter_animate: ^4.5.0
  # Format date/time
  intl: ^0.19.0
  # Lưu trạng thái cục bộ
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
